name: Deploy

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: "17.3.0"
                  cache: yarn

            - name: 🏗️ Prerequisites (Main)
              run: yarn

            - name: 🏗️ Prerequisites (Frontend)
              working-directory: frontend
              run: yarn

            - name: 🏗️ Prerequisites (Backend)
              working-directory: backend
              run: yarn

            - name: 🔨 Build
              run: yarn build

            - name: 🚀 Deploy
              uses: JamesIves/github-pages-deploy-action@4.3.0
              with:
                  branch: gh-pages
                  folder: dist
